# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='wesbite',
            new_name='website',
        ),
    ]
